# -*- coding: utf-8 -*-
"""Copy of chamudithaK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lwUo7MD9ZfCmM1U2Em5pYhfMfz8sZ-Eq
"""

from typing import List

def longest_equal_subarray(arr: List[int]) -> int:
    if not arr:
        return 0



